sonar.projectKey=Spendsmart-Frontend
sonar.projectName=SpendSmart Frontend
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**

# Path to test directories
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Source code encoding
sonar.sourceEncoding=UTF-8

# Server info
sonar.host.url=http://localhost:9000
# sonar.login=sqp_c1550a3b9a02c1ac5a597722e53becf6dd2f5654
